name: full_run-STAGE

on:
    # schedule:
    # * it will run at 1 A.M and 1 P.M
    # - cron:  '00 01,13 * * *'
    workflow_dispatch:
        inputs:
            testList:
                description: 'Test map'
                required: false
                default:
            runId:
                description: 'Run ID - used for PowerBI reporting'
                required: false
                default:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '12'

            - uses: microsoft/playwright-github-action@v1

            - name: Install dependencies
              run: yarn install  --frozen-lockfile

            - name: Export secrets
              run: |

              shell: bash

            - name: Run tests
              run: |
                  echo "startDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
                  yarn jest -i --json --outputFile=artifacts/report.json src/__tests__
              shell: bash

            - name: Merge Reports
              if: always()
              run: |
                  node src/ci-scripts/mergeReports.js
              shell: bash

            - name: Upload artifacts
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: test-artifacts
                  path: artifacts/

            - name: Send Notification to Slack - Failure
              if: ${{ failure() }}
              uses: rtCamp/action-slack-notify@master
              env:
                  SLACK_CHANNEL: wsi-factory-test-results
                  SLACK_COLOR: '#E01E5A'
                  SLACK_TITLE: Test status
                  SLACK_MESSAGE: ':warning: *Repository:* ${{ github.event.repository.name}}  *Result:* ${{ job.status }} :warning:'
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  MSG_MINIMAL: false

            - name: Send Notification to Slack - Success
              uses: rtCamp/action-slack-notify@master
              env:
                  SLACK_CHANNEL: wsi-factory-test-results
                  SLACK_COLOR: '#80FF33'
                  SLACK_TITLE: Test status
                  SLACK_MESSAGE: ':success-icon: *Repository:* ${{ github.event.repository.name}}  *Result:* ${{ job.status }} :success-icon:'
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  MSG_MINIMAL: false

            - name: Send Report to Power BI
              if: always()
              run: |
                  echo $startDate
                  export "customerID=${{ secrets.CONFIG_CUSTOMER_ID }}" >> $GITHUB_ENV
                  export serverVersionTest=$(curl -k -s https:///$customerID.us.iws.cloud.com/status/up | jq -r '.version')
                  echo $serverVersionTest
                  export runNumber="${{ github.run_number }}"
                  export workflowName="${{ github.workflow }}"
                  export repositoryName="${{ github.event.repository.name}}"
                  export endDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
                  export parentalRunId=${{ github.event.inputs.runId }}

                  node fullrunReport.js --buildID="$runNumber" --startTime=$startTime --customerID=$customerID --serverVersionTest=$serverVersionTest --endTime=$endTime --jobName=$jobName --parentalRunId=$parentalRunId --powerBiApiKey="${{ secrets.POWER_BI_API_KEY }}"

              shell: bash
