# This is a basic workflow to help you run your tests on multiple envs or customers.

name: Multiple Envs

on:
  workflow_dispatch:
    inputs:
      dev:
        description: "config DEV"
        required: true
        default: "none"
      qa:
        description: "config QA"
        required: true
        default: "none"
      prod:
        description: "config PROD"
        required: true
        default: "none"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs: ${{github.event.inputs.*}}
        exclude:
          - envs: "none"
    environment:
      name: ${{ matrix.envs }}
      

    steps:
      - uses: actions/checkout@v2
      - name: Print environment name
        run: |
          echo "Running on ${{ matrix.envs }}"
