name: Multiple Envs

on:
  workflow_dispatch:
    inputs:
      dev:
        description: "config DEV"
        required: true
        default: 'DEV'
      qa:
        description: "config QA"
        required: true
        default: 'QA'
      prod:
        description: "config PROD"
        required: rrue
        default: "PROD"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs: ["${{github.event.inputs.dev}}", "${{github.event.inputs.qa}}", "${{github.event.inputs.prod}}"]
        exclude:
          - envs: ""
    environment:
      name: ${{ matrix.envs }}
      

    steps:
      - uses: actions/checkout@v2
      - name: Print environment name
        run: |
          echo "Runs on ${{environment.name}}"
