name: e2e_test

on:
    # schedule:
    # * it will run at 1 A.M and 1 P.M
    # - cron:  '00 01,13 * * *'
    workflow_dispatch:
        inputs:
            testList:
                description: 'Test map'
                required: false
                default:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
            tags:
                description: 'Test scenario tags'
    repository_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '12'

            - uses: microsoft/playwright-github-action@v1

            - name: Install dependencies
              run: yarn install  --frozen-lockfile

            - name: Run tests
              run: |
                  echo "startDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
                  yarn jest -i --json --outputFile=artifacts/report.json --testNamePattern="${{github.event.inputs.testList}}" src/__tests__
              shell: bash

            - name: Upload artifacts
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: test-artifacts
                  path: artifacts/
